# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'create_item.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ItemWin(object):
    def setupUi(self, ItemWin):
        ItemWin.setObjectName("ItemWin")
        ItemWin.resize(800, 600)
        ItemWin.setMinimumSize(QtCore.QSize(800, 600))
        ItemWin.setMaximumSize(QtCore.QSize(800, 600))
        ItemWin.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(ItemWin)
        self.centralwidget.setObjectName("centralwidget")
        self.create_task = QtWidgets.QPushButton(self.centralwidget)
        self.create_task.setGeometry(QtCore.QRect(50, 510, 701, 41))
        self.create_task.setStyleSheet("background-color: rgb(226, 226, 226);\n"
"font: 57 13pt \"raleway\";\n"
"border-radius : 12px;")
        self.create_task.setObjectName("create_task")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 50, 191, 51))
        self.label.setStyleSheet("color: rgb(200, 200, 200);\n"
"font: 16pt \"Raleway\";\n"
"border-radius : 12px;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 130, 191, 51))
        self.label_2.setStyleSheet("color: rgb(200, 200, 200);\n"
"font: 16pt \"Raleway\";\n"
"border-radius : 12px;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.nameitem = QtWidgets.QLineEdit(self.centralwidget)
        self.nameitem.setGeometry(QtCore.QRect(240, 50, 511, 51))
        self.nameitem.setStyleSheet("background-color: rgb(225, 225, 225);\n"
"font: 22pt \"MS Serif\";\n"
"text-align: center;\n"
"border-radius: 10px;\n"
"")
        self.nameitem.setAlignment(QtCore.Qt.AlignCenter)
        self.nameitem.setObjectName("nameitem")
        self.path = QtWidgets.QLineEdit(self.centralwidget)
        self.path.setGeometry(QtCore.QRect(240, 130, 511, 51))
        self.path.setStyleSheet("background-color: rgb(225, 225, 225);\n"
"font: 22pt \"MS Serif\";\n"
"text-align: center;\n"
"border-radius: 10px;\n"
"")
        self.path.setAlignment(QtCore.Qt.AlignCenter)
        self.path.setObjectName("path")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 210, 191, 51))
        self.label_3.setStyleSheet("color: rgb(200, 200, 200);\n"
"font: 16pt \"Raleway\";\n"
"border-radius : 12px;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.location = QtWidgets.QLineEdit(self.centralwidget)
        self.location.setGeometry(QtCore.QRect(240, 210, 511, 51))
        self.location.setStyleSheet("background-color: rgb(225, 225, 225);\n"
"font: 22pt \"MS Serif\";\n"
"text-align: center;\n"
"border-radius: 10px;\n"
"")
        self.location.setAlignment(QtCore.Qt.AlignCenter)
        self.location.setObjectName("location")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 290, 191, 51))
        self.label_4.setStyleSheet("color: rgb(200, 200, 200);\n"
"font: 16pt \"Raleway\";\n"
"border-radius : 12px;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.rare = QtWidgets.QLineEdit(self.centralwidget)
        self.rare.setGeometry(QtCore.QRect(240, 290, 511, 51))
        self.rare.setStyleSheet("background-color: rgb(225, 225, 225);\n"
"font: 22pt \"MS Serif\";\n"
"text-align: center;\n"
"border-radius: 10px;\n"
"")
        self.rare.setAlignment(QtCore.Qt.AlignCenter)
        self.rare.setObjectName("rare")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 370, 191, 51))
        self.label_5.setStyleSheet("color: rgb(200, 200, 200);\n"
"font: 16pt \"Raleway\";\n"
"border-radius : 12px;")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.describe = QtWidgets.QLineEdit(self.centralwidget)
        self.describe.setGeometry(QtCore.QRect(240, 370, 511, 51))
        self.describe.setStyleSheet("background-color: rgb(225, 225, 225);\n"
"font: 22pt \"MS Serif\";\n"
"text-align: center;\n"
"border-radius: 10px;\n"
"")
        self.describe.setAlignment(QtCore.Qt.AlignCenter)
        self.describe.setObjectName("describe")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(330, 450, 91, 31))
        self.label_6.setStyleSheet("color: rgb(200, 200, 200);\n"
"font: 16pt \"Raleway\";\n"
"border-radius : 12px;")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(590, 450, 91, 31))
        self.label_7.setStyleSheet("color: rgb(200, 200, 200);\n"
"font: 16pt \"Raleway\";\n"
"border-radius : 12px;")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.buy = QtWidgets.QLineEdit(self.centralwidget)
        self.buy.setGeometry(QtCore.QRect(430, 440, 61, 51))
        self.buy.setStyleSheet("background-color: rgb(225, 225, 225);\n"
"font: 22pt \"MS Serif\";\n"
"text-align: center;\n"
"border-radius: 10px;\n"
"")
        self.buy.setAlignment(QtCore.Qt.AlignCenter)
        self.buy.setObjectName("buy")
        self.sell = QtWidgets.QLineEdit(self.centralwidget)
        self.sell.setGeometry(QtCore.QRect(690, 440, 61, 51))
        self.sell.setStyleSheet("background-color: rgb(225, 225, 225);\n"
"font: 22pt \"MS Serif\";\n"
"text-align: center;\n"
"border-radius: 10px;\n"
"")
        self.sell.setAlignment(QtCore.Qt.AlignCenter)
        self.sell.setObjectName("sell")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(50, 450, 161, 31))
        self.label_8.setStyleSheet("color: rgb(200, 200, 200);\n"
"font: 16pt \"Raleway\";\n"
"border-radius : 12px;")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.use = QtWidgets.QRadioButton(self.centralwidget)
        self.use.setGeometry(QtCore.QRect(230, 456, 20, 21))
        self.use.setIconSize(QtCore.QSize(24, 24))
        self.use.setChecked(False)
        self.use.setObjectName("use")

        ItemWin.setCentralWidget(self.centralwidget)

        self.retranslateUi(ItemWin)
        QtCore.QMetaObject.connectSlotsByName(ItemWin)

    def retranslateUi(self, ItemWin):
        _translate = QtCore.QCoreApplication.translate
        ItemWin.setWindowTitle(_translate("ItemWin", "Создание предмета"))
        self.create_task.setText(_translate("ItemWin", "Создать"))
        self.label.setText(_translate("ItemWin", "Название предмета"))
        self.label_2.setText(_translate("ItemWin", "Path"))
        self.label_3.setText(_translate("ItemWin", "Локация"))
        self.label_4.setText(_translate("ItemWin", "Редкость"))
        self.label_5.setText(_translate("ItemWin", "Описание"))
        self.label_6.setText(_translate("ItemWin", "Купить"))
        self.label_7.setText(_translate("ItemWin", "Продать"))
        self.label_8.setText(_translate("ItemWin", "Использование"))
        self.use.setText(_translate("ItemWin", "RadioButton"))
