# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'create_task.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys


class Ui_Taskwin(object):
    def setupUi(self, Taskwin):
        Taskwin.setObjectName("Taskwin")
        Taskwin.resize(800, 600)
        Taskwin.setMinimumSize(QtCore.QSize(800, 600))
        Taskwin.setMaximumSize(QtCore.QSize(800, 600))
        Taskwin.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(Taskwin)
        self.centralwidget.setObjectName("centralwidget")
        self.create_task = QtWidgets.QPushButton(self.centralwidget)
        self.create_task.setGeometry(QtCore.QRect(50, 510, 701, 41))
        self.create_task.setStyleSheet("background-color: rgb(226, 226, 226);\n"
"font: 57 13pt \"raleway\";\n"
"border-radius : 12px;")
        self.create_task.setObjectName("create_task")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 60, 191, 51))
        self.label.setStyleSheet("color: rgb(200, 200, 200);\n"
"font: 16pt \"Raleway\";\n"
"border-radius : 12px;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 140, 191, 51))
        self.label_2.setStyleSheet("color: rgb(200, 200, 200);\n"
"font: 16pt \"Raleway\";\n"
"border-radius : 12px;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.create_und_task = QtWidgets.QPushButton(self.centralwidget)
        self.create_und_task.setGeometry(QtCore.QRect(240, 220, 251, 51))
        self.create_und_task.setStyleSheet("background-color: rgb(226, 226, 226);\n"
"font: 57 13pt \"raleway\";\n"
"border-radius : 12px;")
        self.create_und_task.setObjectName("create_und_task")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 220, 191, 51))
        self.label_3.setStyleSheet("color: rgb(200, 200, 200);\n"
"font: 16pt \"Raleway\";\n"
"border-radius : 12px;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 380, 191, 51))
        self.label_4.setStyleSheet("color: rgb(200, 200, 200);\n"
"font: 16pt \"Raleway\";\n"
"border-radius : 12px;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 300, 191, 51))
        self.label_5.setStyleSheet("color: rgb(200, 200, 200);\n"
"font: 16pt \"Raleway\";\n"
"border-radius : 12px;")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.button_reward = QtWidgets.QPushButton(self.centralwidget)
        self.button_reward.setGeometry(QtCore.QRect(240, 300, 201, 51))
        self.button_reward.setStyleSheet("background-color: rgb(226, 226, 226);\n"
"font: 57 13pt \"raleway\";\n"
"border-radius : 12px;")
        self.button_reward.setObjectName("button_reward")
        self.nametask = QtWidgets.QLineEdit(self.centralwidget)
        self.nametask.setGeometry(QtCore.QRect(240, 60, 511, 51))
        self.nametask.setStyleSheet("background-color: rgb(225, 225, 225);\n"
"font: 22pt \"MS Serif\";\n"
"text-align: center;\n"
"border-radius: 10px;\n"
"")
        self.nametask.setAlignment(QtCore.Qt.AlignCenter)
        self.nametask.setObjectName("nametask")
        self.taskfrom = QtWidgets.QLineEdit(self.centralwidget)
        self.taskfrom.setGeometry(QtCore.QRect(240, 140, 511, 51))
        self.taskfrom.setStyleSheet("background-color: rgb(225, 225, 225);\n"
"font: 22pt \"MS Serif\";\n"
"text-align: center;\n"
"border-radius: 10px;\n"
"")
        self.taskfrom.setAlignment(QtCore.Qt.AlignCenter)
        self.taskfrom.setObjectName("taskfrom")
        self.number_task = QtWidgets.QLineEdit(self.centralwidget)
        self.number_task.setGeometry(QtCore.QRect(240, 380, 81, 51))
        self.number_task.setStyleSheet("background-color: rgb(225, 225, 225);\n"
"font: 22pt \"MS Serif\";\n"
"text-align: center;\n"
"border-radius: 10px;\n"
"")
        self.number_task.setAlignment(QtCore.Qt.AlignCenter)
        self.number_task.setObjectName("number_task")
        Taskwin.setCentralWidget(self.centralwidget)

        self.retranslateUi(Taskwin)
        QtCore.QMetaObject.connectSlotsByName(Taskwin)

    def retranslateUi(self, Taskwin):
        _translate = QtCore.QCoreApplication.translate
        Taskwin.setWindowTitle(_translate("Taskwin", "Создание задания"))
        self.create_task.setText(_translate("Taskwin", "Создать"))
        self.label.setText(_translate("Taskwin", "Название задания"))
        self.label_2.setText(_translate("Taskwin", "От кого задание"))
        self.create_und_task.setText(_translate("Taskwin", "Редактировать подазадания"))
        self.label_3.setText(_translate("Taskwin", "Подзаданий: 0"))
        self.label_4.setText(_translate("Taskwin", "Номер задания"))
        self.label_5.setText(_translate("Taskwin", "Наград: "))
        self.button_reward.setText(_translate("Taskwin", "Редактировать награду"))
