# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'redact_und_tasks.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UndTasksWin(object):
    def __init__(self):
        self.count = 1
    def setupUi(self, UndTasksWin):
        UndTasksWin.setObjectName("UndTasksWin")
        UndTasksWin.resize(800, 600)
        UndTasksWin.setMinimumSize(QtCore.QSize(800, 600))
        UndTasksWin.setMaximumSize(QtCore.QSize(800, 600))
        UndTasksWin.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(UndTasksWin)
        self.centralwidget.setObjectName("centralwidget")
        self.savebtn = QtWidgets.QPushButton(self.centralwidget)
        self.savebtn.setGeometry(QtCore.QRect(50, 520, 701, 41))
        self.savebtn.setStyleSheet("background-color: rgb(226, 226, 226);\n"
"font: 57 13pt \"raleway\";\n"
"border-radius : 12px;")
        self.savebtn.setObjectName("savebtn")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(320, 40, 171, 51))
        self.label.setStyleSheet("color: rgb(225, 225, 225);\n"
"font: 22pt \"MS Serif\";\n"
"text-align: center;\n"
"border-radius: 10px;\n"
"")
        self.label.setObjectName("label")
        self.create_btn = QtWidgets.QPushButton(self.centralwidget)
        self.create_btn.setGeometry(QtCore.QRect(50, 460, 701, 41))
        self.create_btn.setStyleSheet("background-color: rgb(226, 226, 226);\n"
"font: 57 13pt \"raleway\";\n"
"border-radius : 12px;")
        self.create_btn.setFlat(False)
        self.create_btn.setObjectName("create_btn")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(50, 100, 701, 341))
        self.tableWidget.setStyleSheet("background-color: rgb(225, 225, 225);\n"
"font: 22pt \"MS Serif\";\n"
"text-align: center;\n"
"border-radius: 10px;\n"
"")

        self.tableWidget.setRowCount(self.count)

        self.tableWidget.setColumnCount(2)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(342)
        UndTasksWin.setCentralWidget(self.centralwidget)

        self.retranslateUi(UndTasksWin)
        QtCore.QMetaObject.connectSlotsByName(UndTasksWin)

    def retranslateUi(self, UndTasksWin):
        _translate = QtCore.QCoreApplication.translate
        UndTasksWin.setWindowTitle(_translate("UndTasksWin", "Редактирование подзаданий"))
        self.savebtn.setText(_translate("UndTasksWin", "Сохранить"))
        self.label.setText(_translate("UndTasksWin", "Подзадания"))
        self.create_btn.setText(_translate("UndTasksWin", "Создать"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("UndTasksWin", "Название"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("UndTasksWin", "Описание"))
