# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'redact_rewards.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RewardsWin(object):
    def setupUi(self, RewardsWin):
        RewardsWin.setObjectName("RewardsWin")
        RewardsWin.resize(800, 600)
        RewardsWin.setMinimumSize(QtCore.QSize(800, 600))
        RewardsWin.setMaximumSize(QtCore.QSize(800, 600))
        RewardsWin.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(RewardsWin)
        self.centralwidget.setObjectName("centralwidget")
        self.savebtn = QtWidgets.QPushButton(self.centralwidget)
        self.savebtn.setGeometry(QtCore.QRect(50, 520, 701, 41))
        self.savebtn.setStyleSheet("background-color: rgb(226, 226, 226);\n"
"font: 57 13pt \"raleway\";\n"
"border-radius : 12px;")
        self.savebtn.setObjectName("savebtn")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(320, 40, 171, 51))
        self.label.setStyleSheet("color: rgb(225, 225, 225);\n"
"font: 22pt \"MS Serif\";\n"
"text-align: center;\n"
"border-radius: 10px;\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 230, 171, 51))
        self.label_2.setStyleSheet("color: rgb(225, 225, 225);\n"
"font: 22pt \"MS Serif\";\n"
"text-align: center;\n"
"border-radius: 10px;\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 320, 171, 51))
        self.label_3.setStyleSheet("color: rgb(225, 225, 225);\n"
"font: 22pt \"MS Serif\";\n"
"text-align: center;\n"
"border-radius: 10px;\n"
"")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.reward1 = QtWidgets.QLineEdit(self.centralwidget)
        self.reward1.setGeometry(QtCore.QRect(240, 230, 141, 61))
        self.reward1.setStyleSheet("background-color: rgb(225, 225, 225);\n"
"font: 22pt \"MS Serif\";\n"
"text-align: center;\n"
"border-radius: 10px;\n"
"")
        self.reward1.setObjectName("reward1")
        self.reward2 = QtWidgets.QLineEdit(self.centralwidget)
        self.reward2.setGeometry(QtCore.QRect(240, 310, 141, 61))
        self.reward2.setStyleSheet("background-color: rgb(225, 225, 225);\n"
"font: 22pt \"MS Serif\";\n"
"text-align: center;\n"
"border-radius: 10px;\n"
"")
        self.reward2.setObjectName("reward2")
        self.countreward1 = QtWidgets.QLineEdit(self.centralwidget)
        self.countreward1.setGeometry(QtCore.QRect(400, 230, 141, 61))
        self.countreward1.setStyleSheet("background-color: rgb(225, 225, 225);\n"
"font: 22pt \"MS Serif\";\n"
"text-align: center;\n"
"border-radius: 10px;\n"
"")
        self.countreward1.setObjectName("countreward1")
        self.countreward2 = QtWidgets.QLineEdit(self.centralwidget)
        self.countreward2.setGeometry(QtCore.QRect(400, 310, 141, 61))
        self.countreward2.setStyleSheet("background-color: rgb(225, 225, 225);\n"
"font: 22pt \"MS Serif\";\n"
"text-align: center;\n"
"border-radius: 10px;\n"
"")
        self.countreward2.setObjectName("countreward2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(250, 150, 131, 51))
        self.label_4.setStyleSheet("color: rgb(225, 225, 225);\n"
"font: 22pt \"MS Serif\";\n"
"text-align: center;\n"
"border-radius: 10px;\n"
"")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(400, 150, 131, 51))
        self.label_5.setStyleSheet("color: rgb(225, 225, 225);\n"
"font: 18pt \"MS Serif\";\n"
"text-align: center;\n"
"border-radius: 10px;\n"
"")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        RewardsWin.setCentralWidget(self.centralwidget)

        self.retranslateUi(RewardsWin)
        QtCore.QMetaObject.connectSlotsByName(RewardsWin)

    def retranslateUi(self, RewardsWin):
        _translate = QtCore.QCoreApplication.translate
        RewardsWin.setWindowTitle(_translate("RewardsWin", "Награды"))
        self.savebtn.setText(_translate("RewardsWin", "Сохранить"))
        self.label.setText(_translate("RewardsWin", "Награды"))
        self.label_2.setText(_translate("RewardsWin", "Награда 1"))
        self.label_3.setText(_translate("RewardsWin", "Награда 2"))
        self.label_4.setText(_translate("RewardsWin", "Тип"))
        self.label_5.setText(_translate("RewardsWin", "Количество"))
